import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsBoolean,
  IsDateString,
  IsEnum,
  IsNumber,
  IsOptional,
  IsString,
  Min,
  Max,
  ValidateNested,
  IsUUID,
  MaxLength,
  MinLength,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import { StockMovementType } from '@prisma/client';

// ==================== BATCH MANAGEMENT DTOs ====================

export class BatchDto {
  @ApiPropertyOptional({
    description: 'Batch number/lot code. Auto-generated by the server when omitted.',
  })
  @IsOptional()
  @IsString()
  @MaxLength(100, { message: 'Batch number must not exceed 100 characters' })
  batchNumber?: string;

  @ApiProperty({ description: 'Quantity in this batch' })
  @IsNumber({ maxDecimalPlaces: 3 }, { message: 'Quantity must have up to 3 decimal places' })
  @Min(0.001, { message: 'Quantity must be at least 0.001' })
  @Max(10000000, { message: 'Quantity cannot exceed 10,000,000' })
  @Type(() => Number)
  quantity: number;

  @ApiPropertyOptional({
    description: 'Unit of measurement for the quantity (piece, box, carton, etc.)',
    default: 'piece'
  })
  @IsOptional()
  @IsString()
  @MaxLength(20, { message: 'Unit must not exceed 20 characters' })
  unit?: string;

  @ApiPropertyOptional({
    description: 'Conversion factor: how many base units per this unit (e.g., 12 pieces per box)',
  })
  @IsOptional()
  @IsNumber({ maxDecimalPlaces: 3 }, { message: 'Conversion factor must have up to 3 decimal places' })
  @Min(0.001, { message: 'Conversion factor must be at least 0.001' })
  @Max(10000, { message: 'Conversion factor cannot exceed 10,000' })
  @Type(() => Number)
  unitsPerQuantity?: number;

  @ApiPropertyOptional({ description: 'Batch expiry date (ISO format)' })
  @IsOptional()
  @IsDateString({}, { message: 'Expiry date must be a valid ISO 8601 date' })
  expiryDate?: string;

  @ApiPropertyOptional({ description: 'Manufacture date (ISO format)' })
  @IsOptional()
  @IsDateString({}, { message: 'Manufacture date must be a valid ISO 8601 date' })
  manufactureDate?: string;

  @ApiPropertyOptional({ description: 'Cost price for this batch' })
  @IsOptional()
  @IsNumber({ maxDecimalPlaces: 2 }, { message: 'Cost price must have up to 2 decimal places' })
  @Min(0, { message: 'Cost price cannot be negative' })
  @Max(10000000, { message: 'Cost price cannot exceed 10,000,000' })
  @Type(() => Number)
  costPrice?: number;

  @ApiPropertyOptional({ description: 'Supplier reference or invoice number' })
  @IsOptional()
  @IsString()
  @MaxLength(100, { message: 'Supplier reference must not exceed 100 characters' })
  supplierRef?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(500, { message: 'Notes must not exceed 500 characters' })
  notes?: string;
}

export class ReceiveBatchDto {
  @ApiProperty()
  @IsUUID('4', { message: 'Branch ID must be a valid UUID' })
  branchId: string;

  @ApiProperty()
  @IsUUID('4', { message: 'Product ID must be a valid UUID' })
  productId: string;

  @ApiProperty({ type: [BatchDto] })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => BatchDto)
  @ArrayMinSize(1, { message: 'At least one batch is required' })
  @ArrayMaxSize(100, { message: 'Cannot receive more than 100 batches at once' })
  batches: BatchDto[];

  @ApiPropertyOptional({ description: 'Reference (e.g., PO number, invoice)' })
  @IsOptional()
  @IsString()
  @MaxLength(100, { message: 'Reference must not exceed 100 characters' })
  reference?: string;
}

export class UpdateBatchDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber({ maxDecimalPlaces: 3 })
  @Min(0)
  @Max(10000000)
  @Type(() => Number)
  quantity?: number;

  @ApiPropertyOptional()
  @IsOptional()
  @IsDateString({}, { message: 'Expiry date must be a valid ISO 8601 date' })
  expiryDate?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsBoolean()
  isBlocked?: boolean;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(500, { message: 'Notes must not exceed 500 characters' })
  notes?: string;
}

export class ExpiryDashboardQueryDto {
  @ApiProperty()
  @IsUUID('4', { message: 'Branch ID must be a valid UUID' })
  branchId: string;

  @ApiPropertyOptional({ description: 'Filter by zone: expired, 30days, 60days, 90days' })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  zone?: 'expired' | '30days' | '60days' | '90days';

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(200, { message: 'Search query must not exceed 200 characters' })
  search?: string;

  @ApiPropertyOptional({ default: 1 })
  @IsOptional()
  @IsNumber({}, { message: 'Page must be a number' })
  @Min(1, { message: 'Page must be at least 1' })
  @Max(10000, { message: 'Page cannot exceed 10000' })
  @Type(() => Number)
  page?: number;

  @ApiPropertyOptional({ default: 50 })
  @IsOptional()
  @IsNumber({}, { message: 'Limit must be a number' })
  @Min(1, { message: 'Limit must be at least 1' })
  @Max(500, { message: 'Limit cannot exceed 500' })
  @Type(() => Number)
  limit?: number;
}

// Stock Adjustment DTOs
export class StockAdjustmentItemDto {
  @ApiProperty()
  @IsUUID('4', { message: 'Product ID must be a valid UUID' })
  productId: string;

  @ApiProperty({ description: 'New stock quantity (absolute value)' })
  @IsNumber({ maxDecimalPlaces: 3 }, { message: 'Quantity must have up to 3 decimal places' })
  @Min(0, { message: 'Quantity cannot be negative' })
  @Max(10000000, { message: 'Quantity cannot exceed 10,000,000' })
  @Type(() => Number)
  quantity: number;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(500, { message: 'Notes must not exceed 500 characters' })
  notes?: string;
}

export class StockAdjustmentDto {
  @ApiProperty()
  @IsUUID('4', { message: 'Branch ID must be a valid UUID' })
  branchId: string;

  @ApiProperty({ enum: StockMovementType })
  @IsEnum(StockMovementType, { message: 'Invalid stock movement type' })
  type: StockMovementType;

  @ApiProperty({ type: [StockAdjustmentItemDto] })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => StockAdjustmentItemDto)
  @ArrayMinSize(1, { message: 'At least one item is required' })
  @ArrayMaxSize(500, { message: 'Cannot adjust more than 500 items at once' })
  items: StockAdjustmentItemDto[];

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(100, { message: 'Reference must not exceed 100 characters' })
  reference?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(1000, { message: 'Notes must not exceed 1000 characters' })
  notes?: string;
}

// Stock Transfer DTOs
export class TransferItemDto {
  @ApiProperty()
  @IsUUID('4', { message: 'Product ID must be a valid UUID' })
  productId: string;

  @ApiProperty()
  @IsNumber({ maxDecimalPlaces: 3 }, { message: 'Quantity must have up to 3 decimal places' })
  @Min(0.001, { message: 'Quantity must be at least 0.001' })
  @Max(10000000, { message: 'Quantity cannot exceed 10,000,000' })
  @Type(() => Number)
  quantity: number;
}

export class CreateTransferDto {
  @ApiProperty()
  @IsUUID('4', { message: 'From branch ID must be a valid UUID' })
  fromBranchId: string;

  @ApiProperty()
  @IsUUID('4', { message: 'To branch ID must be a valid UUID' })
  toBranchId: string;

  @ApiProperty({ type: [TransferItemDto] })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => TransferItemDto)
  @ArrayMinSize(1, { message: 'At least one item is required' })
  @ArrayMaxSize(500, { message: 'Cannot transfer more than 500 items at once' })
  items: TransferItemDto[];

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(1000, { message: 'Notes must not exceed 1000 characters' })
  notes?: string;
}

export class ReceiveTransferDto {
  @ApiProperty({ description: 'Received quantities per item' })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => TransferItemDto)
  @ArrayMinSize(1, { message: 'At least one item is required' })
  receivedItems: TransferItemDto[];

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(1000, { message: 'Notes must not exceed 1000 characters' })
  notes?: string;
}

// Query DTOs
export class StockQueryDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(200, { message: 'Search query must not exceed 200 characters' })
  search?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsUUID('4', { message: 'Category ID must be a valid UUID' })
  categoryId?: string;

  @ApiPropertyOptional({ description: 'Only show low stock items' })
  @IsOptional()
  @IsBoolean()
  lowStock?: boolean;

  @ApiPropertyOptional({ default: 1 })
  @IsOptional()
  @IsNumber({}, { message: 'Page must be a number' })
  @Min(1, { message: 'Page must be at least 1' })
  @Max(10000, { message: 'Page cannot exceed 10000' })
  @Type(() => Number)
  page?: number;

  @ApiPropertyOptional({ default: 50 })
  @IsOptional()
  @IsNumber({}, { message: 'Limit must be a number' })
  @Min(1, { message: 'Limit must be at least 1' })
  @Max(500, { message: 'Limit cannot exceed 500' })
  @Type(() => Number)
  limit?: number;
}

// Stock Request DTOs
export class CreateStockRequestDto {
  @ApiProperty({ description: 'Branch ID where stock is needed' })
  @IsUUID('4', { message: 'Branch ID must be a valid UUID' })
  branchId: string;

  @ApiProperty({ description: 'Product ID being requested' })
  @IsUUID('4', { message: 'Product ID must be a valid UUID' })
  productId: string;

  @ApiProperty({ description: 'Quantity requested' })
  @IsNumber({ maxDecimalPlaces: 3 }, { message: 'Quantity must have up to 3 decimal places' })
  @Min(0.001, { message: 'Quantity must be at least 0.001' })
  @Max(10000000, { message: 'Quantity cannot exceed 10,000,000' })
  @Type(() => Number)
  quantity: number;

  @ApiPropertyOptional({ description: 'Unit of measurement', default: 'piece' })
  @IsOptional()
  @IsString()
  @MaxLength(20, { message: 'Unit must not exceed 20 characters' })
  unit?: string;

  @ApiPropertyOptional({ description: 'Reason for the request' })
  @IsOptional()
  @IsString()
  @MinLength(10, { message: 'Reason must be at least 10 characters' })
  @MaxLength(500, { message: 'Reason must not exceed 500 characters' })
  reason?: string;

  @ApiPropertyOptional({
    description: 'Request priority',
    enum: ['low', 'normal', 'high', 'urgent'],
    default: 'normal'
  })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  priority?: string;

  @ApiPropertyOptional({ description: 'Image URLs (e.g., empty shelf photos)', type: [String] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  @MaxLength(500, { each: true, message: 'Each image URL must not exceed 500 characters' })
  images?: string[];
}

export class UpdateStockRequestDto {
  @ApiPropertyOptional()
  @IsOptional()
  @IsNumber({ maxDecimalPlaces: 3 })
  @Min(0.001)
  @Max(10000000)
  @Type(() => Number)
  quantity?: number;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(20)
  unit?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MinLength(10)
  @MaxLength(500)
  reason?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  @MaxLength(20)
  priority?: string;

  @ApiPropertyOptional({ type: [String] })
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  @MaxLength(500, { each: true })
  images?: string[];
}

export class ResolveStockRequestDto {
  @ApiProperty({
    description: 'Resolution action',
    enum: ['APPROVED', 'REJECTED', 'FULFILLED']
  })
  @IsString()
  @IsEnum(['APPROVED', 'REJECTED', 'FULFILLED'], { message: 'Status must be APPROVED, REJECTED, or FULFILLED' })
  status: 'APPROVED' | 'REJECTED' | 'FULFILLED';

  @ApiPropertyOptional({ description: 'Resolution notes or reason' })
  @IsOptional()
  @IsString()
  @MinLength(10, { message: 'Resolution notes must be at least 10 characters' })
  @MaxLength(1000, { message: 'Resolution notes must not exceed 1000 characters' })
  resolution?: string;
}

export class StockRequestQueryDto {
  @ApiPropertyOptional({ description: 'Filter by branch ID' })
  @IsOptional()
  @IsUUID('4', { message: 'Branch ID must be a valid UUID' })
  branchId?: string;

  @ApiPropertyOptional({
    description: 'Filter by status',
    enum: ['PENDING', 'APPROVED', 'REJECTED', 'FULFILLED', 'CANCELLED']
  })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  status?: string;

  @ApiPropertyOptional({ description: 'Filter by priority' })
  @IsOptional()
  @IsString()
  @MaxLength(20)
  priority?: string;

  @ApiPropertyOptional({ description: 'Filter by product ID' })
  @IsOptional()
  @IsUUID('4', { message: 'Product ID must be a valid UUID' })
  productId?: string;

  @ApiPropertyOptional({ description: 'Filter by requester user ID' })
  @IsOptional()
  @IsUUID('4', { message: 'User ID must be a valid UUID' })
  requestedById?: string;

  @ApiPropertyOptional({ description: 'Page number', default: 1 })
  @IsOptional()
  @IsNumber({}, { message: 'Page must be a number' })
  @Min(1, { message: 'Page must be at least 1' })
  @Max(10000, { message: 'Page cannot exceed 10000' })
  @Type(() => Number)
  page?: number;

  @ApiPropertyOptional({ description: 'Items per page', default: 20 })
  @IsOptional()
  @IsNumber({}, { message: 'Limit must be a number' })
  @Min(1, { message: 'Limit must be at least 1' })
  @Max(500, { message: 'Limit cannot exceed 500' })
  @Type(() => Number)
  limit?: number;
}

// Response DTOs (no validation needed)
export class StockItemResponseDto {
  @ApiProperty()
  productId: string;

  @ApiProperty()
  sku: string;

  @ApiProperty()
  productName: string;

  @ApiProperty()
  quantity: number;

  @ApiProperty()
  reservedQty: number;

  @ApiProperty()
  availableQty: number;

  @ApiProperty()
  minStock: number;

  @ApiProperty()
  isLowStock: boolean;

  @ApiProperty()
  unit: string;

  @ApiProperty()
  costPrice?: number;

  @ApiProperty()
  stockValue?: number;
}

export class StockMovementResponseDto {
  @ApiProperty()
  id: string;

  @ApiProperty()
  productId: string;

  @ApiProperty()
  productName: string;

  @ApiProperty()
  type: StockMovementType;

  @ApiProperty()
  quantity: number;

  @ApiProperty()
  previousQty: number;

  @ApiProperty()
  newQty: number;

  @ApiProperty()
  reference?: string;

  @ApiProperty()
  notes?: string;

  @ApiProperty()
  createdAt: Date;

  @ApiProperty()
  createdBy?: string;
}

export class TransferResponseDto {
  @ApiProperty()
  id: string;

  @ApiProperty()
  fromBranchId: string;

  @ApiProperty()
  fromBranchName: string;

  @ApiProperty()
  toBranchId: string;

  @ApiProperty()
  toBranchName: string;

  @ApiProperty()
  status: string;

  @ApiProperty()
  notes?: string;

  @ApiProperty()
  items: Array<{
    productId: string;
    productName: string;
    requestedQty: number;
    sentQty?: number;
    receivedQty?: number;
  }>;

  @ApiProperty()
  createdAt: Date;

  @ApiProperty()
  createdBy: string;
}

// ==================== BATCH RESPONSE DTOs ====================

export class BatchResponseDto {
  @ApiProperty()
  id: string;

  @ApiProperty()
  batchNumber: string;

  @ApiProperty()
  quantity: number;

  @ApiProperty()
  reservedQty: number;

  @ApiProperty()
  availableQty: number;

  @ApiProperty()
  expiryDate?: Date;

  @ApiProperty()
  manufactureDate?: Date;

  @ApiProperty()
  costPrice?: number;

  @ApiProperty()
  supplierRef?: string;

  @ApiProperty()
  notes?: string;

  @ApiProperty()
  isBlocked: boolean;

  @ApiProperty()
  isExpired: boolean;

  @ApiProperty()
  daysUntilExpiry?: number;

  @ApiProperty()
  expiryStatus: 'expired' | 'expiring_soon' | 'good';

  @ApiProperty()
  createdAt: Date;
}

export class StockWithBatchesResponseDto {
  @ApiProperty()
  productId: string;

  @ApiProperty()
  sku: string;

  @ApiProperty()
  productName: string;

  @ApiProperty()
  totalQuantity: number;

  @ApiProperty()
  totalReservedQty: number;

  @ApiProperty()
  totalAvailableQty: number;

  @ApiProperty({ type: [BatchResponseDto] })
  batches: BatchResponseDto[];

  @ApiProperty()
  hasExpiredBatches: boolean;

  @ApiProperty()
  hasExpiringSoonBatches: boolean;
}

export class ExpiryDashboardItemDto {
  @ApiProperty()
  productId: string;

  @ApiProperty()
  productName: string;

  @ApiProperty()
  sku: string;

  @ApiProperty()
  batchNumber: string;

  @ApiProperty()
  quantity: number;

  @ApiProperty()
  expiryDate?: Date;

  @ApiProperty()
  daysUntilExpiry?: number;

  @ApiProperty()
  expiryStatus: 'expired' | 'critical' | 'warning' | 'good';

  @ApiProperty()
  isBlocked: boolean;

  @ApiProperty()
  costValue?: number;
}

export class ExpiryDashboardResponseDto {
  @ApiProperty({ type: [ExpiryDashboardItemDto] })
  items: ExpiryDashboardItemDto[];

  @ApiProperty()
  total: number;

  @ApiProperty()
  page: number;

  @ApiProperty()
  limit: number;

  @ApiProperty()
  totalPages: number;

  @ApiProperty()
  summary: {
    expiredCount: number;
    expiredValue: number;
    expiring30Days: number;
    expiring30DaysValue: number;
    expiring60Days: number;
    expiring60DaysValue: number;
    expiring90Days: number;
    expiring90DaysValue: number;
  };
}

export class StockRequestResponseDto {
  @ApiProperty()
  id: string;

  @ApiProperty()
  branchId: string;

  @ApiProperty()
  branchName: string;

  @ApiProperty()
  requestedById: string;

  @ApiProperty()
  requestedByName: string;

  @ApiProperty()
  productId: string;

  @ApiProperty()
  productName: string;

  @ApiProperty()
  productSku: string;

  @ApiProperty()
  quantity: number;

  @ApiProperty()
  unit: string;

  @ApiProperty()
  reason?: string;

  @ApiProperty()
  priority: string;

  @ApiProperty()
  status: string;

  @ApiProperty({ type: [String] })
  images: string[];

  @ApiProperty()
  resolvedById?: string;

  @ApiProperty()
  resolvedByName?: string;

  @ApiProperty()
  resolvedAt?: Date;

  @ApiProperty()
  resolution?: string;

  @ApiProperty()
  createdAt: Date;

  @ApiProperty()
  updatedAt: Date;

  @ApiProperty()
  currentStock?: number;
}
