import { SyncEventType } from './dto/sync.dto';
import { SyncService } from './sync.service';

describe('SyncService pull pagination', () => {
  it('does not skip events that share a page-boundary timestamp', async () => {
    const timestamp = new Date('2026-01-01T00:00:00.000Z');
    const movements = ['a', 'b', 'c'].map((id) => ({
      id,
      branchId: 'branch-1',
      productId: 'product-1',
      newQty: id === 'a' ? 1 : id === 'b' ? 2 : 3,
      createdAt: timestamp,
      product: { id: 'product-1', stock: [{ quantity: 3 }] },
    }));

    const stockMovement = {
      findMany: jest.fn(async (args: any) => {
        const boundary = (args.where.OR as any[]).find(
          (condition) => condition.id?.gt,
        )?.id.gt as string | undefined;
        return movements
          .filter((movement) => boundary == null || movement.id > boundary)
          .slice(0, args.take);
      }),
    };
    const prisma = { stockMovement } as any;
    const service = new SyncService(
      prisma,
      {} as any,
      {} as any,
      {} as any,
      {} as any,
    );

    const firstPage = await service.pullEvents(undefined, 'branch-1', {
      since: '1970-01-01T00:00:00.000Z',
      eventTypes: [SyncEventType.STOCK_ADJUSTED],
      limit: 2,
    });
    expect(firstPage.events.map((event) => event.entityId)).toEqual(['a', 'b']);
    expect(firstPage.hasMore).toBe(true);
    expect(firstPage.nextCursor).toContain('|STOCK_ADJUSTED|b');

    const secondPage = await service.pullEvents(undefined, 'branch-1', {
      since: firstPage.nextCursor,
      eventTypes: [SyncEventType.STOCK_ADJUSTED],
      limit: 2,
    });
    expect(secondPage.events.map((event) => event.entityId)).toEqual(['c']);
    expect(secondPage.hasMore).toBe(false);
  });
});

describe('SyncService pushed entity identity', () => {
  it('uses the local sale id instead of the queue event id as offlineId', async () => {
    const salesService = {
      createSale: jest.fn(async () => ({ id: 'server-sale-1' })),
    };
    const prisma = {
      branch: {
        findUnique: jest.fn(async () => ({ tenantId: 'tenant-1' })),
      },
    } as any;
    const service = new SyncService(
      prisma,
      {} as any,
      salesService as any,
      {} as any,
      {} as any,
    );

    await (service as any).processEvent(
      {
        eventId: 'queue-event-1',
        eventType: SyncEventType.SALE_CREATED,
        payload: {
          id: 'local-sale-1',
          offlineId: 'local-sale-1',
          cashierId: 'user-1',
          items: [],
          paymentMethod: 'CASH',
          totalAmount: 10,
        },
      },
      'branch-1',
      'device-1',
    );

    expect(salesService.createSale).toHaveBeenCalledWith(
      'user-1',
      'tenant-1',
      expect.objectContaining({ offlineId: 'local-sale-1' }),
    );
  });

  it('preserves a customer id generated by the originating device', async () => {
    const customer = {
      create: jest.fn(async ({ data }) => ({ id: data.id })),
    };
    const prisma = {
      branch: {
        findUnique: jest.fn(async () => ({ tenantId: 'tenant-1' })),
      },
      customer,
    } as any;
    const service = new SyncService(
      prisma,
      {} as any,
      {} as any,
      {} as any,
      {} as any,
    );

    await (service as any).processEvent(
      {
        eventId: 'queue-event-2',
        eventType: SyncEventType.CUSTOMER_CREATED,
        payload: { id: 'customer-1', name: 'Alex' },
      },
      'branch-1',
      'device-1',
    );

    expect(customer.create).toHaveBeenCalledWith({
      data: expect.objectContaining({ id: 'customer-1', tenantId: 'tenant-1' }),
    });
  });
});
